### PR TITLE
[SYCLomatic] Fix the parsing of device lambda with cuda-8.0 on windows

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by ShengchenJ — APPROVED** [review]
LGTM

**Review by zhimingwang36 — CHANGES_REQUESTED** [review]
Please dig more detail to see the difference between 8.0 and 9.0.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
