### PR TITLE
[SYCLomatic] Enable "-fgpu-exclude-wrong-side-overloads" by default

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Comment by zhimingwang36** [comment]
there is conflicting,  need rebase.

**Comment by zhiweij1** [comment]
@zhimingwang36 
> there is conflicting, need rebase.

This PR depends on https://github.com/oneapi-src/SYCLomatic/pull/1377 , after https://github.com/oneapi-src/SYCLomatic/pull/1377 merged, I can rebase this one.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Review by tomflinda — APPROVED** [review]
LGTM

**Pull request merged**
