### PR TITLE
[SYCLomatic] Fix DeclStmt migration in the body of lambda expression

### PR DESCRIPTION
**Pull request by delecui**

### CODE REVIEW

**Review by AndyCHHuang — APPROVED** [review]
LGTM

**Review by ziranzha — APPROVED** [review]
LGTM

**Review by ziranzha — CHANGES_REQUESTED** [review]
Need sign off

**Comment by delecui** [comment]
Pushed new commit by force to add sign-off.
No code changes.

**Review by ziranzha — APPROVED** [review]
LGTM

**Pull request merged**
