### PR TITLE
[SYCLomatic] Add support for cuda-11.7

### PR DESCRIPTION
**Pull request by wenhuiNi**
Add support for cuda-11.7
Do ninja check-clang-c2s tests：38 Unsupported, 639 passed (cuda-11.6,cuda-11,7)

### CODE REVIEW

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Review by ziranzha — APPROVED** [review]
Need submit commit with sign-off

**Review by ziranzha — CHANGES_REQUESTED** [review]
Need submit commit with sign-off

**Review by ziranzha — APPROVED** [review]
LGTM

**Pull request merged**
