### PR TITLE
[SYCLomatic] Emit warning for unsupported cuRand types

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Comment by zhiweij1** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/1231

**Review by tangjj11 — APPROVED** [review]
lgtm

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
