### PR TITLE
[NFC][SYCLomatic][DOC] Update API migration status April 2024

### PR DESCRIPTION
**Pull request by yihwang-nv**

### CODE REVIEW

**Review by tangjj11 — APPROVED** [review]
cudaBindTextureToMipmappedArray and 4 math APIs LGTM.

**Review by zhiweij1 — APPROVED** [review]

**Comment by oscarbg** [comment]
Hi,
sorry for asking here, it's nice to see monthly progress of this migration tool, but can I ask how this progress is correlated to Intel Oneapi releases? i.e. using current/latest Intel OneAPI 2024.1, and once this PR is merged and using a release with a daily build will be able to migrate and run projects using cudaBindTextureToMipmappedArray for ex.?
thanks..

**Comment by zhiweij1** [comment]
> Hi, sorry for asking here, it's nice to see monthly progress of this migration tool, but can I ask how this progress is correlated to Intel Oneapi releases? i.e. using current/latest Intel OneAPI 2024.1, and once this PR is merged and using a release with a daily build will be able to migrate and run projects using cudaBindTextureToMipmappedArray for ex.? thanks..

Hi @oscarbg , the migration of `cudaBindTextureToMipmappedArray ` is already supported. The most accurate method to 
 check if an API is supported to be migrated is searching its name in `APINames*.inc` files (E.g., https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/lib/DPCT/APINames.inc#L354). Because the changes in `APINames*.inc` files are almost always contained in the migration implementation PR. So using any daily build after that time can migrate the API.

And checking the files updated in this PR can also get the same information. But there will be some lag since they are updated monthly.

For the oneAPI release, I think 2024.2 will contain these supports.

**Review by tomflinda — APPROVED** [review]
LGTM

**Comment by oscarbg** [comment]
> > Hi, sorry for asking here, it's nice to see monthly progress of this migration tool, but can I ask how this progress is correlated to Intel Oneapi releases? i.e. using current/latest Intel OneAPI 2024.1, and once this PR is merged and using a release with a daily build will be able to migrate and run projects using cudaBindTextureToMipmappedArray for ex.? thanks..
> 
> Hi @oscarbg , the migration of `cudaBindTextureToMipmappedArray ` is already supported. The most accurate method to check if an API is supported to be migrated is searching its name in `APINames*.inc` files (E.g., https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/lib/DPCT/APINames.inc#L354). Because the changes in `APINames*.inc` files are almost always contained in the migration implementation PR. So using any daily build after that time can migrate the API.
> 
> And checking the files updated in this PR can also get the same information. But there will be some lag since they are updated monthly.
> 
> For the oneAPI release, I think 2024.2 will contain these supports.

thanks for answering! very informative..

**Review by ziranzha — APPROVED** [review]

**Pull request merged**
