### PR TITLE
[SYCLomatic][NFC][DOC] Update API migration status August 2024

### PR DESCRIPTION
**Pull request by yihwang-nv**

### CODE REVIEW

**Review by zhiweij1 — APPROVED** [review]

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by zhiweij1 — APPROVED** [review]

**Review by intwanghao — COMMENTED** [review]
dnn part is correct

**Review by tomflinda — APPROVED** [review]
thrust confirmed, LGTM

**Review by AndyCHHuang — APPROVED** [review]
LGTM

**Review by zhimingwang36 — APPROVED** [review]

**Pull request merged**
