### PR TITLE
[SYCLomatic] Fix constant_iterator: declare __my_value_ as non const

### PR DESCRIPTION
**Pull request by SergeyKopienko**

### CODE REVIEW

**Comment by timmiesmith** [comment]
The patch looks good to me. Thank you, @SergeyKopienko .

**Comment by SergeyKopienko** [comment]
@oneapi-src/syclomatic-reviewers, could anybody please approve this PR ?

**Review by 0x12CC — CHANGES_REQUESTED** [review]
The `SYCLomatic/clang/test/dpct/check_header_files.cpp` LIT test is currently failing. Please update `SYCLomatic/clang/test/dpct/helper_files_ref/include/dpl_extras/iterators.h:109:2` to match the change you made.

**Comment by 0x12CC** [comment]
Also, please sign your commits. You can find more information about the required sign-off here: https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/CONTRIBUTING.md#sign-your-work.

**Comment by SergeyKopienko** [comment]
> The `SYCLomatic/clang/test/dpct/check_header_files.cpp` LIT test is currently failing. Please update `SYCLomatic/clang/test/dpct/helper_files_ref/include/dpl_extras/iterators.h:109:2` to match the change you made.

done.

**Comment by SergeyKopienko** [comment]
> Also, please sign your commits. You can find more information about the required sign-off here: https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/CONTRIBUTING.md#sign-your-work.

done

**Comment by SergeyKopienko** [comment]
> The patch looks good to me. Thank you, @SergeyKopienko .

@timmiesmith, could you please press the Approve button at this PR ?

**Review by timmiesmith — APPROVED** [review]
LGTM

**Comment by SergeyKopienko** [comment]
https://github.com/orgs/oneapi-src/teams/syclomatic-reviewers, could anybody please approve this PR ?
Commit in this PR signed by me.
Second place in code at SYCLomatic/clang/test/dpct/helper_files_ref/include/dpl_extras/iterators.h:109 fixed.
This commit already approved by @timmiesmith

**Review by 0x12CC — APPROVED** [review]

**Comment by SergeyKopienko** [comment]
@0x12CC could you please merge this PR? Seems that I haven't rights for that's.

**Comment by SergeyKopienko** [comment]
@0x12CC Could you please explain why I doesn't see this PR in the https://github.com/oneapi-src/SYCLomatic.git ?

**Pull request closed without merging**
