### PR TITLE
[SYCLomatic] Migrate __grid_constant__ annotation

### LINKED ISSUE #497: error: unknown type name '__grid_constant__'
Please see https://github.com/intel/llvm/issues/7998

### PR DESCRIPTION
**Pull request by 0x12CC**
Signed-off-by: Michael Aziz <michael.aziz@intel.com>

### CODE REVIEW

**Review by jzc — APPROVED** [review]

**Review by LU-JOHN — APPROVED** [review]
LGTM

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Comment by zjin-lcf** [comment]
@0x12CC  Could you please add some descriptions to the pull request to explain the migration ?  Thanks.

**Comment by 0x12CC** [comment]
@zjin-lcf, this migration removes the `__grid_constant__` annotation. Removing this annotation does not change the semantics of the kernel since all parameters that use the annotation must also be `const`.

**Pull request merged**
