### PR TITLE
[SYCLomatic] Enabled 1 thrust API and 2 type migration, refined 3 thrust API migration.

### PR DESCRIPTION
**Pull request by zhiweij1**
thrust::not_equal_to
thrust::constant_iterator
thrust::find
thrust::sort_by_key
thrust::inner_product
thrust::reduce_by_key

Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Comment by zhiweij1** [comment]
Test PR: https://github.com/oneapi-src/SYCLomatic-test/pull/56

**Review by AndyCHHuang — APPROVED** [review]
LGTM

**Review by ziranzha — APPROVED** [review]
LGTM

**Comment by zhiweij1** [comment]
The two failures are due to MKL bug. They are known issues.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
