### PR TITLE
[SYCLomatic] Use ldc*n instead of 0 for parameter stridec in oneapi::mkl::blas::column_major::dgmm_batch

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Review by intwanghao — APPROVED** [review]
LGTM

**Comment by zhiweij1** [comment]
The failures of BLAS related cases in help_function suite are expected.
Those test cases need to be updated.

**Review by ziranzha — APPROVED** [review]
LGTM

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
