### PR TITLE
[SYCLomatic] Fix 4 lit cases and all migration on windows with cuda-12.1

### PR DESCRIPTION
**Pull request by zhiweij1**
Signed-off-by: Jiang, Zhiwei <zhiwei.jiang@intel.com>

### CODE REVIEW

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by wenhuiNi — APPROVED** [review]

**Comment by wenhuiNi** [comment]
But why did the test of #748  not report this error？

**Comment by zhiweij1** [comment]
> But why did the test of #748 not report this error？

I guess at that time the CI was still using 12.0.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
