### PR TITLE
[SYCLomatic] Fix API cuda::atomic_thread_fence

### PR DESCRIPTION
**Pull request by wenhuiNi**
Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

### CODE REVIEW

**Comment by wenhuiNi** [comment]
Hello, I added a new mechanism CheckArgIsDefault to check whether a parameter of a call  uses default parameter. Please help review this modification. If it is the same as the previous mechanism or has a better implementation, please comment it.

**Comment by wenhuiNi** [comment]
fix lit test case of api cuda::atomic_thread_fence, and add support using namespace for cuda::atomic_thread_fence and its enum param

**Review by AndyCHHuang — APPROVED** [review]
LGTM

**Review by ziranzha — APPROVED** [review]
LGTM

**Pull request merged**
