### PR TITLE
[SYCLomatic] Support migration of asm inst: vadd2/vsub2/vabsdiff2/vmin2/vmax2.

### PR DESCRIPTION
**Pull request by tangjj11**
Signed-off-by: Tang, Jiajun jiajun.tang@intel.com

### CODE REVIEW

**Review by yihwang-nv — APPROVED** [review]
LGTM

**Review by wenhuiNi — APPROVED** [review]

**Comment by jinz2014** [comment]
@tangjj11  I have a question. Is your pull request related to #1417 ?

**Comment by tangjj11** [comment]
> @tangjj11 I have a question. Is your pull request related to #1417 ?

@jinz2014 No, because these APIs has not been supported by SYCL side in https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/ext/intel/math/imf_simd.hpp now.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
