### PR TITLE
[SYCLomatic]Fix use of wrong return value in atomic_compare_exchange_strong

### PR DESCRIPTION
**Pull request by wenhuiNi**
Signed-off-by: Ni, Wenhui <wenhui.ni@intel.com>

### CODE REVIEW

**Review by AndyCHHuang — APPROVED** [review]
LGTM

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by zhimingwang36 — APPROVED** [review]
We need add test case to catch this kind issue.

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
